# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 15 ]
    name: Compile Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@main
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: mvn clean compile
  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Project
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Cache Maven Packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: [ app/target/legacy.jar *.md ]
    needs: build
    name: Package Artifact
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp ${{ matrix.files }} staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
